
# Возможность отключать ваулт. Если на сервере уже используется другой плагин на экономику
# Если на сервере есть другая экономика, то при снятии баланса может быть такое, что
# ваши коины будут сниматься.
# Купил ты блок алмаза в магазинчике за внутриигровую валюту за 5000 дримиков (которые равны 5 рублям),
# а у тебя снимается 5к коинов, которые стоят 1 коин за рубль :/
# Поэтому нужно исключить все подобные моменты
vault-support: true
# Подключение к базе данных
database:
  host: localhost
  port: 3306
  login: root
  password: root
  database: dreamtime
messages:
  get:
    message: "&aВаш баланс: %coins% %curr_name%"
    currency:
      word: "коин"
      a: ""
      b: "а"
      c: "ов"
  get-other:
    message: "&aБаланс игрока %player%: %coins%  %curr_name%"
    currency:
      word: "коин"
      a: ""
      b: "а"
      c: "ов"
  set:
    from:
      message: "&aИгроку %player% установлено %coins%  %curr_name%"
    to:
      message: "&aИгрок %player% установил вам %coins%  %curr_name%"
    currency:
      word: "коин"
      a: ""
      b: "а"
      c: "ов"
  add:
    from:
      message: "&aИгроку %player% добавлено %coins%  %curr_name%"
    to:
      message: "&aИгрок %player% добавил вам %coins%  %curr_name%"
    currency:
      word: "коин"
      a: ""
      b: "а"
      c: "ов"
  reset:
    from:
      message: "&aБаланс игрока %player% обнулён"
    to:
      message: "&a%player% обнулил ваш балас"
    currency:
      word: "коин"
      a: ""
      b: "а"
      c: "ов"
  # Если /money take будет использоваться чтобы отнять деньги у игрока через консоль, то
  # можно сделать сообщения на подобии "у вас снято %coins% %curr_name%".
  # Но сообщения тому, кто забрал коины, всё равно лучше оставить.
  # Будет удобнее, если админ #забирает деньги, чтобы ему писалось то,
  # сколько он забрал и у кого. Для проверки, на всякий случай.
  # То же самое, касается остальных сообщений.
  # При выдаче коинов, например,1 можно написать "Вам было начислено N коинов"
  # Именно такие сообщения написаны, дабы показать какие плейсхолдеры возможно использовать.
  # То, что они значат, думаю, понятно из контекста...
  take:
    from:
      message: "&aУ игрока %player% было забрано %coins%  %curr_name%"
    to:
      message: "&a%player% забрал у вас %coins%  %curr_name%"
    currency:
      word: "коин"
      a: ""
      b: "а"
      c: "ов"
  no-perm: "&cУ вас недостаточно прав"
  player-not-found: "&cИгрок не найден"
  not-a-player: "§cYou have to be player to use this command!"

  # Если вместо числа, человек ввёл что-то другое
  value-error: "§cОшибка в значении!"
  wrong-args: "Неверные аргументы команды. введите /help ля-ля-ля то-по-ля..."
