
database:
  host: localhost
  port: 3306
  login: root
  password: root
  database: dreamtime
messages:
  get:
    message: "&aВаш баланс: %coins% %curr_name%"
    currency:
      word: "коин"
      a: ""
      b: "а"
      c: "ов"
  get-other:
    message: "&aБаланс игрока %player%: %coins%  %curr_name%"
    currency:
      word: "коин"
      a: ""
      b: "а"
      c: "ов"
  set:
    from:
      message: "&aИгроку %player% установлено %coins%  %curr_name%"
    to:
      message: "&aИгрок %player% установил вам %coins%  %curr_name%"
    currency:
      word: "коин"
      a: ""
      b: "а"
      c: "ов"
  add:
    from:
      message: "&aИгроку %player% добавлено %coins%  %curr_name%"
    to:
      message: "&aИгрок %player% добавил вам %coins%  %curr_name%"
    currency:
      word: "коин"
      a: ""
      b: "а"
      c: "ов"
  reset:
    from:
      message: "&aБаланс игрока %player% обнулён"
    to:
      message: "&a%player% обнулил ваш балас"
    currency:
      word: "коин"
      a: ""
      b: "а"
      c: "ов"
  take:
    from:
      message: "&aУ игрока %player% было забрано %coins%  %curr_name%"
      no-money: "У игрока %player% недостаточно коинов"
    to:
      message: "&a%player% забрал у вас %coins%  %curr_name%"
      no-money: "&cНедостаточно коинов!"
    currency:
      word: "коин"
      a: ""
      b: "а"
      c: "ов"
  no-perm: "&cУ вас недостаточно прав"
  player-not-found: "&cИгрок не найден"
  not-a-player: "§cYou have to be player to use this command!"

  # Если вместо числа, человек ввёл что-то другое
  value-error: "§cОшибка в значении!"
  wrong-args: "Неверные аргументы команды. введите /help ля-ля-ля то-по-ля..."
