name: ${project.name}
version: ${project.version}
main: su.dreamtime.dreamiki.Main
softdepend: [Vault, PlaceholderAPI]
api-version: 1.13
load: STARTUP
depend:
  - DreamTimeAPI
commands:
  donatewallet:
    description: ""
    aliases: [dw]

permissions:
  dreamiki.get:
    default: true
    description: "to get your balance"
  dreamiki.get.other:
    default: op
    description: "to get balance of other players"
  dreamiki.help:
    default: true
    description: "to display available commands"
  dreamiki.set:
    default: op
    description: "to set coins to players"
  dreamiki.add:
    default: op
    description: "to add coins to players"
  dreamiki.reset:
    default: op
    description: "to reset coins of players"
  dreamiki.take:
    default: op
    description: "to take coins from players"
  dreamiki.reload:
    default: op
    description: "reload configuration"